name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-cd:
    uses: qntx/workflows/.github/workflows/release-rust.yml@main
    with:
      bin: skills
      package: skills-cli
